CREATE TABLE Theater (
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(60) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    LOT_NUMBER VARCHAR(100) NOT NULL,
    XPOS DOUBLE,
    YPOS DOUBLE,
    OPEN BOOLEAN,
    LINK VARCHAR(100),
    PRIMARY KEY (ID)
);